### ISSUE TITLE
why only need one step of denoising

### ISSUE THREAD

**Issue by jiqizaisikao** [koa-fin/dva#1]
May I ask why only need one step of denoising to get the result? Does the last step no longer need to add noise to x? If so, what is the effect of adding noise to x during training?

**Comment by koa-fin** [comment]
The effect of adding noise to **x** during training is to train the model to handle stochasticity in the <ins>input</ins> price data. At the same time, we also train a denoising function to remove noise from **y’** to handle stochasticity in the <ins>target</ins> price data. 

At test-time, we use this trained denoising function to “denoise” the final prediction, making it more generalizable.

You can read more details of our work in the [paper](https://arxiv.org/abs/2309.00073).
