### ISSUE TITLE
Why do input and output lengths remain consistent？

### ISSUE THREAD

**Issue by 137315198** [koa-fin/dva#2]
May I ask why the parameter settings for history and output length remain consistent? Have you ever tried a longer history? Or is a longer historical window not effective? For example, a history window of 96 and a prediction window of 10.

**Comment by koa-fin** [comment]
Our work was inspired by image reconstruction models, which typically handle same-sized input and output images before performing scaling. Using the same lengths allowed us to try other techniques from this domain during our research. 

For this particular model, using different history and output lengths should work, even though we did not run these experiments. You can experiment with different output lengths using the additional argument _--prediction_length xx_

Feel free to try it and help to report your results here :)
