### ISSUE TITLE
The process of preprocessing dataset

### ISSUE THREAD

**Issue by lucasguo** [koa-fin/dva#5]
It's really a great idea that using image generation algorithm on financial data!

I want to use this model on other financial market.

And I found he dataset under data folder seem being preprocessed. 
In the pdf, I've seen

```
Additionally, given that we
are interested in predicting the percentage returns, the open, high
and low prices are normalized by the previous closing price, e.g.,
𝑜𝑡 = 𝑜𝑡 /𝑐𝑡−1
```
If so, there should not be any negative values. However there are many negative values in dataset files.

Do I miss something?

Thanks for your help.

**Comment by koa-fin** [comment]
You can treat $o\_t$, $h\_t$, $l\_t$ and $r\_t$ as the <ins>**percentage change**</ins> in Open, High, Low, Close prices respectively. 

Using absolute values, the normalization method would be $o\_t = {\tilde{o}\_t / c\_{t-1}}-1$, where $\tilde{o}\_t$ is the absolute Open price. 

Thanks for clarifying.
