### ISSUE TITLE
Discrepancy between your data and real world data

### ISSUE THREAD

**Issue by vincent05r** [koa-fin/dva#6]
Hi, I was just examining your data and I found out that your data is very different to real world data. It seems like there is some kind of preprocessing done on the dataset however it is not mentioned in the paper. Could you please explain? Thanks!
In addition, I tried your model on the real world data with the exact format and same stock, it doesnt even manage to learn. Thanks!

**Comment by koa-fin** [comment]
The preprocessing step was mentioned in the paper under section **3.1 Problem Formulation**.
